import './globals.scss'
import styles from './layout.module.scss'
import { Henny_Penny, Nanum_Gothic } from 'next/font/google'

// Metadata

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// Fonts

const Henny_PennyFont = Henny_Penny({
    weight: '400',
    subsets: ['latin']
})

const Nanum_GothicFont = Nanum_Gothic({
    weight: '700',
    subsets: ['latin']
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
            <body>
                <header className={styles.appHeader}>
                    <strong className={Henny_PennyFont.className}>Moodboarding</strong>
                    <div className={`${styles.appHeader_linkContainer} ${Nanum_GothicFont.className}`}>
                        <span className={styles.appHeader_link}>Explore</span>
                        <span className={styles.appHeader_link}>Quadros</span>
                    </div>
                </header>
                <main className={styles.appMain}>
                    {children}
                </main>

                <div className={styles.globalDisplayFilter}></div>
            </body>
        </html>
    )
}
