import './globals.css'
import styles from './layout.module.scss'
import localFont from 'next/font/local'

const Belanosima = localFont({ src: '../assets/fonts/Belanosima-Regular.ttf' })

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <header className={styles.app_header}>
          <strong className={Belanosima.className}>Moodboarding</strong>
        </header>
        <main className={styles.app_main}>
          {children}
        </main>
      </body>
    </html>
  )
}
